language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "5.0.0"
before_script:
  - npm install -g gulp
script: gulp compile

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8