language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "4"
before_script:
  - $CXX --version
  - npm install -g gulp

script: gulp compile
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y
addons:
    code_climate:
        repo_token: 052a5ae4de33b8e16e3d18e84c09d9c6079d26c923daa19fba8a7cc5a756f671

sudo: false
