language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "4"
before_script:
  - $CXX --version
  - npm install -g gulp

script: gulp compile

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
addons:
    code_climate:
        repo_token: 052a5ae4de33b8e16e3d18e84c09d9c6079d26c923daa19fba8a7cc5a756f671

sudo: false
