export { default as App } from './app.block';
export { default as Welcome } from './sections/welcome.block';
export { default as Contact } from './sections/contact.block';
export { default as Login } from './sections/login.block';
export { default as Admin } from './sections/admin.block';
export { default as Dashboard } from './sections/admin/dashboard.block';
export { default as Users } from './sections/admin/users.block';
export { default as Permissions } from './sections/admin/permissions.block';
export { default as AssignAuth } from './sections/admin/modals/assign.auth.block';