export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';
export const DATA_REQUESTED = 'DATA_REQUESTED';
export const DATA_SERVER = 'DATA_SERVER';

